### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [SatelliteQE/5minute#64]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.33. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary vminute -w /tmp/ext vminute==0.2.33
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting vminute==0.2.33
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/ea2/291e7833d14cb/vminute-0.2.33.tar.gz (17 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-d9a65xj8/vminute/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-d9a65xj8/vminute/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-d9a65xj8/vminute/pip-egg-info
         cwd: /tmp/pip-wheel-d9a65xj8/vminute/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-d9a65xj8/vminute/setup.py", line 12, in <module>
        with open(path.join(here, 'requirements.txt'), encoding='utf-8') as f:
      File "/usr/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-d9a65xj8/vminute/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
It would appear this doesn't happen with current versions of setuptools/pip on a repo build.
